import { db, souqProductsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { logger } from "./logger";

const BOOKS_SEED = [
  // ── Personal Development & Productivity ──────────────────────────────────
  {
    slug: "atomic-habits-arabic",
    name: "العادات الذرية",
    category: "book" as const,
    description: "كيف تبني عادات جيدة وتتخلص من السيئة — جيمس كلير",
    longDescription: "يقدم جيمس كلير دليلاً عملياً لبناء عادات صغيرة تحدث تحولات ضخمة. يشرح الكتاب نظام الحلقات العادية الأربعة وكيف تستطيع تعديلها لتحقيق أهدافك الشخصية والمهنية.",
    author: "جيمس كلير",
    coverImageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    price: "34.99",
    isFeatured: true,
    tags: '{"تطوير ذاتي","عادات","إنتاجية"}',
  },
  {
    slug: "deep-work-arabic",
    name: "العمل العميق",
    category: "book" as const,
    description: "قواعد النجاح في عالم مشتت — كال نيوبورت",
    longDescription: "يستكشف كال نيوبورت مفهوم العمل العميق وكيف أن القدرة على التركيز الكامل بدون تشتت أصبحت المهارة الأكثر قيمة في الاقتصاد الحديث.",
    author: "كال نيوبورت",
    coverImageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
    price: "29.99",
    isFeatured: false,
    tags: '{"إنتاجية","تركيز","نجاح"}',
  },
  {
    slug: "mindset-arabic",
    name: "العقلية — قوة التفكير النمائي",
    category: "book" as const,
    description: "كارول دويك — سيكولوجية النجاح",
    longDescription: "تكشف عالمة النفس كارول دويك عن أثر العقلية على النجاح، وتوضح الفرق الجوهري بين عقلية النمو وعقلية الثبوت وكيف يمكن تنمية الأولى.",
    author: "كارول دويك",
    coverImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    price: "27.99",
    isFeatured: false,
    tags: '{"تطوير ذاتي","سيكولوجية","نجاح"}',
  },
  {
    slug: "ikigai-arabic",
    name: "إيكيغاي — سر طول العمر الياباني",
    category: "book" as const,
    description: "الفلسفة اليابانية لإيجاد معنى الحياة",
    longDescription: "يستكشف الكتاب مفهوم الإيكيغاي الياباني — سبب الاستيقاظ صباحاً — ويشرح كيف يجد الناس في أوكيناوا هدفهم وسعادتهم وطول أعمارهم.",
    author: "هيكتور غارسيا وفرانشيسك ميرالس",
    coverImageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    price: "24.99",
    isFeatured: false,
    tags: '{"فلسفة","سعادة","تطوير ذاتي"}',
  },
  {
    slug: "subtle-art-arabic",
    name: "الفن الرفيع لعدم الاكتراث",
    category: "book" as const,
    description: "مارك مانسون — نهج مغاير لعيش حياة أفضل",
    longDescription: "بأسلوب صريح وجريء، يتحدى مارك مانسون الفكرة الشائعة عن الإيجابية ويطرح رؤية مختلفة للسعادة قائمة على القبول واختيار ما تهتم به حقاً.",
    author: "مارك مانسون",
    coverImageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400",
    price: "26.99",
    isFeatured: true,
    tags: '{"تطوير ذاتي","فلسفة"}',
  },
  {
    slug: "man-search-meaning-arabic",
    name: "الإنسان يبحث عن معنى",
    category: "book" as const,
    description: "فيكتور فرانكل — رحلة النجاة من المحرقة ودروس اللوغوثيرابي",
    longDescription: "سيرة وتحليل نفسي استثنائي لعالم النفس الناجي من معسكرات الاعتقال النازية، يستكشف كيف يجد الإنسان المعنى في أقسى الظروف.",
    author: "فيكتور فرانكل",
    coverImageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
    price: "22.99",
    isFeatured: true,
    tags: '{"فلسفة","سيكولوجية","إلهام"}',
  },
  // ── Business & Finance ────────────────────────────────────────────────────
  {
    slug: "zero-to-one-arabic",
    name: "من الصفر إلى الواحد",
    category: "book" as const,
    description: "بيتر ثيل — ملاحظات حول الشركات الناشئة وكيف تبني المستقبل",
    longDescription: "يشارك بيتر ثيل المؤسس المشارك لـ PayPal أفكاره الخلافية حول الابتكار وبناء شركات احتكارية تخلق قيمة حقيقية.",
    author: "بيتر ثيل",
    coverImageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400",
    price: "32.99",
    isFeatured: true,
    tags: '{"أعمال","ريادة","تقنية"}',
  },
  {
    slug: "rich-dad-poor-dad-arabic",
    name: "أبي الغني أبي الفقير",
    category: "book" as const,
    description: "روبرت كيوساكي — ما يعلمه الأغنياء لأبنائهم",
    longDescription: "الكلاسيكية التي غيرت مفهوم الثروة لملايين القراء حول العالم، تشرح الفرق بين الأصول والخصوم وكيف تفكر في المال بطريقة الأثرياء.",
    author: "روبرت كيوساكي",
    coverImageUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400",
    price: "29.99",
    isFeatured: true,
    tags: '{"مال","استثمار","ثروة"}',
  },
  {
    slug: "psychology-of-money-arabic",
    name: "سيكولوجية المال",
    category: "book" as const,
    description: "مورغان هاوسل — الدروس الخالدة حول الثروة والجشع والسعادة",
    longDescription: "يطرح الكتاب نظرة جديدة على علاقة البشر بالمال ويكشف عن الأنماط النفسية التي تقود قراراتنا المالية وكيف نتخذ قرارات أفضل.",
    author: "مورغان هاوسل",
    coverImageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400",
    price: "31.99",
    isFeatured: false,
    tags: '{"مال","سيكولوجية","استثمار"}',
  },
  {
    slug: "thinking-fast-slow-arabic",
    name: "التفكير السريع والبطيء",
    category: "book" as const,
    description: "دانييل كانيمان — النوبل في علم الاقتصاد السلوكي",
    longDescription: "يأخذنا الحائز على جائزة نوبل في رحلة مذهلة عبر عقلي البشر: النظام السريع العاطفي والنظام البطيء المنطقي وكيف يشكلان قراراتنا اليومية.",
    author: "دانييل كانيمان",
    coverImageUrl: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400",
    price: "35.99",
    isFeatured: false,
    tags: '{"سيكولوجية","اقتصاد","قرارات"}',
  },
  {
    slug: "lean-startup-arabic",
    name: "الشركة الناشئة الرشيقة",
    category: "book" as const,
    description: "إريك ريس — كيف يتعلم رواد الأعمال العصريون ويقيسون ويحولون اتجاههم",
    longDescription: "منهج ثوري في بناء الشركات الناشئة يعتمد على التعلم السريع والقياس الدقيق بدلاً من الخطط التفصيلية.",
    author: "إريك ريس",
    coverImageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400",
    price: "28.99",
    isFeatured: false,
    tags: '{"ريادة","أعمال","ابتكار"}',
  },
  {
    slug: "good-to-great-arabic",
    name: "من الجيد إلى العظيم",
    category: "book" as const,
    description: "جيم كولينز — لماذا تقفز بعض الشركات وأخرى لا تفعل",
    longDescription: "دراسة معمّقة لـ 11 شركة تحولت من متوسطة إلى استثنائية، تكشف العوامل المشتركة التي تميز الشركات العظيمة عن غيرها.",
    author: "جيم كولينز",
    coverImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400",
    price: "33.99",
    isFeatured: false,
    tags: '{"إدارة","أعمال","قيادة"}',
  },
  // ── Crypto & Technology ───────────────────────────────────────────────────
  {
    slug: "bitcoin-standard-arabic",
    name: "معيار البيتكوين",
    category: "book" as const,
    description: "سيفيدين أمووس — النظام المالي اللامركزي",
    longDescription: "يستكشف الكتاب تاريخ المال والمعيار الذهبي ويشرح كيف يمثل البيتكوين أفضل نوع من النقود تطورت عبر التاريخ.",
    author: "سيفيدين أمووس",
    coverImageUrl: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400",
    price: "39.99",
    isFeatured: true,
    tags: '{"بيتكوين","بلوكتشين","مال رقمي"}',
  },
  {
    slug: "crypto-trading-101",
    name: "تداول العملات الرقمية 101",
    category: "book" as const,
    description: "الدليل الشامل للمبتدئين في أسواق الكريبتو",
    longDescription: "يغطي الكتاب أساسيات تداول العملات الرقمية من اختيار المنصة وإدارة المخاطر وتحليل الشارت إلى استراتيجيات التداول اليومي والمتأرجح.",
    author: "أحمد الراشد",
    coverImageUrl: "https://images.unsplash.com/photo-1642104704074-907c0698cbd9?w=400",
    price: "44.99",
    isFeatured: true,
    tags: '{"تداول","كريبتو","استثمار"}',
  },
  {
    slug: "web3-defi-guide",
    name: "دليل Web3 والتمويل اللامركزي",
    category: "book" as const,
    description: "فهم DeFi والـ NFT والـ DAO والمستقبل الرقمي",
    longDescription: "مرجع شامل لعالم Web3 يشرح بأسلوب مبسط مفاهيم التمويل اللامركزي والعقود الذكية والرموز غير القابلة للاستبدال.",
    author: "محمد الأنصاري",
    coverImageUrl: "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=400",
    price: "42.99",
    isFeatured: false,
    tags: '{"Web3","DeFi","بلوكتشين"}',
  },
  {
    slug: "ai-revolution-arabic",
    name: "ثورة الذكاء الاصطناعي",
    category: "book" as const,
    description: "كيف يعيد الذكاء الاصطناعي رسم ملامح الاقتصاد العالمي",
    longDescription: "يستكشف الكتاب التطورات المتسارعة في مجال الذكاء الاصطناعي وتأثيرها على سوق العمل والاقتصاد والحياة اليومية.",
    author: "خالد المنصور",
    coverImageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400",
    price: "36.99",
    isFeatured: false,
    tags: '{"ذكاء اصطناعي","تقنية","مستقبل"}',
  },
  {
    slug: "prompt-engineering-book",
    name: "هندسة البرومبت — التواصل مع الذكاء الاصطناعي",
    category: "book" as const,
    description: "فن استخدام ChatGPT وأدوات الذكاء الاصطناعي باحترافية",
    longDescription: "دليل متقدم لهندسة البرومبت يغطي تقنيات Chain-of-Thought وFew-Shot وZero-Shot مع أمثلة عملية لمختلف المجالات.",
    author: "سارة العلوي",
    coverImageUrl: "https://images.unsplash.com/photo-1671726203454-488ab18f7eda?w=400",
    price: "38.99",
    isFeatured: true,
    tags: '{"ذكاء اصطناعي","تقنية","برمجة"}',
  },
  // ── Arabic Fiction & Literature ───────────────────────────────────────────
  {
    slug: "cities-of-salt-arabic",
    name: "مدن الملح",
    category: "book" as const,
    description: "عبد الرحمن منيف — ملحمة التحول الكبرى في الخليج العربي",
    longDescription: "الرواية الأيقونية في خماسية عبد الرحمن منيف التي ترصد التحولات الاجتماعية الكبرى في المجتمعات الخليجية مع اكتشاف النفط.",
    author: "عبد الرحمن منيف",
    coverImageUrl: "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=400",
    price: "27.99",
    isFeatured: false,
    tags: '{"رواية","أدب عربي","خليج"}',
  },
  {
    slug: "arabian-nights-modern",
    name: "ليالٍ عربية حديثة",
    category: "book" as const,
    description: "مجموعة قصصية من أبرز أقلام الجيل الجديد",
    longDescription: "اثنتا عشرة قصة قصيرة لكتّاب عرب معاصرين تمزج بين الموروث الكلاسيكي والحداثة، تتناول قضايا الهوية والغربة والحب.",
    author: "تأليف مشترك",
    coverImageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400",
    price: "21.99",
    isFeatured: false,
    tags: '{"قصص","أدب عربي","حديث"}',
  },
  {
    slug: "the-yacoubian-building",
    name: "عمارة يعقوبيان",
    category: "book" as const,
    description: "علاء الأسواني — لوحة إنسانية من قلب القاهرة",
    longDescription: "رواية تضج بشخصيات حية تقطن عمارة واحدة في وسط القاهرة وتعكس التناقضات الاجتماعية والسياسية في مصر المعاصرة.",
    author: "علاء الأسواني",
    coverImageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=400",
    price: "23.99",
    isFeatured: false,
    tags: '{"رواية","مصر","أدب عربي"}',
  },
  {
    slug: "the-swallows-of-kabul",
    name: "خرفان المولى",
    category: "book" as const,
    description: "ياسمينة خضرا — رواية شعرية في أزمنة الحرب",
    longDescription: "رواية ياسمينة خضرا الشعرية التي تصف الحياة في ظل الحرب والاحتلال بأسلوب ينتزع الدمعة ويوقظ الضمير.",
    author: "ياسمينة خضرا",
    coverImageUrl: "https://images.unsplash.com/photo-1587513200021-9e2c2a7cc83f?w=400",
    price: "22.99",
    isFeatured: false,
    tags: '{"رواية","أدب","حرب"}',
  },
  {
    slug: "the-alchemist-arabic",
    name: "الخيميائي",
    category: "book" as const,
    description: "باولو كويلو — رحلة الروح نحو قدرها الشخصي",
    longDescription: "الرواية الأكثر مبيعاً في التاريخ، تحكي قصة الراعي الأندلسي سانتياغو في رحلته نحو كنزه الشخصي وما تعلمه من الكون والناس.",
    author: "باولو كويلو",
    coverImageUrl: "https://images.unsplash.com/photo-1533669955142-6a73332af4db?w=400",
    price: "24.99",
    isFeatured: true,
    tags: '{"رواية","إلهام","فلسفة"}',
  },
  {
    slug: "no-longer-human-arabic",
    name: "أنا الإنسان الفاقد",
    category: "book" as const,
    description: "أوساجو دازاي — رواية الاغتراب الياباني الكبرى",
    longDescription: "كلاسيكية يابانية تستكشف العزلة والانفصال عن المجتمع بقلم أحد أكثر الأصوات الأدبية تأثيراً في القرن العشرين.",
    author: "أوساجو دازاي",
    coverImageUrl: "https://images.unsplash.com/photo-1476275466078-4cdc71f21e38?w=400",
    price: "21.99",
    isFeatured: false,
    tags: '{"رواية","أدب ياباني","فلسفة"}',
  },
  // ── History & Civilization ────────────────────────────────────────────────
  {
    slug: "sapiens-arabic",
    name: "العاقل — تاريخ موجز للبشرية",
    category: "book" as const,
    description: "يوفال نوح هراري — رحلة 70000 عام من التاريخ البشري",
    longDescription: "من أبرز الكتب في القرن الحادي والعشرين، يتتبع هراري تطور الإنسان من الصيد والجمع إلى الثورات الزراعية والصناعية والمعرفية.",
    author: "يوفال نوح هراري",
    coverImageUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=400",
    price: "36.99",
    isFeatured: true,
    tags: '{"تاريخ","بشرية","حضارة"}',
  },
  {
    slug: "homo-deus-arabic",
    name: "الإنسان الإله",
    category: "book" as const,
    description: "يوفال نوح هراري — تاريخ موجز للغد",
    longDescription: "يرسم هراري صورة مستقبل البشرية في ضوء الثورة التكنولوجية والبيولوجية ويتساءل: ماذا سيريد الإنسان بعد أن حقق كل ما أراد؟",
    author: "يوفال نوح هراري",
    coverImageUrl: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400",
    price: "36.99",
    isFeatured: false,
    tags: '{"تاريخ","مستقبل","تقنية"}',
  },
  {
    slug: "guns-germs-steel-arabic",
    name: "الأسلحة والجراثيم والفولاذ",
    category: "book" as const,
    description: "جاريد دياموند — مصائر المجتمعات البشرية",
    longDescription: "يجيب الكتاب على سؤال جوهري: لماذا سادت حضارات على أخرى؟ دراسة تاريخية علمية رائدة تغطي 13000 عام من التطور البشري.",
    author: "جاريد دياموند",
    coverImageUrl: "https://images.unsplash.com/photo-1533310266094-8898a03807dd?w=400",
    price: "34.99",
    isFeatured: false,
    tags: '{"تاريخ","حضارة","علم"}',
  },
  {
    slug: "ottoman-empire-arabic",
    name: "تاريخ الدولة العثمانية",
    category: "book" as const,
    description: "دراسة شاملة لستة قرون من الإمبراطورية الإسلامية الكبرى",
    longDescription: "مرجع تاريخي متكامل يتناول صعود الدولة العثمانية وذروة قوتها وأسباب انهيارها وإرثها في المنطقة العربية.",
    author: "خالد الغنامي",
    coverImageUrl: "https://images.unsplash.com/photo-1580711508376-571bcc9c80dc?w=400",
    price: "32.99",
    isFeatured: false,
    tags: '{"تاريخ","عثماني","إسلام"}',
  },
  {
    slug: "arab-history-modern",
    name: "العرب في التاريخ الحديث",
    category: "book" as const,
    description: "قراءة نقدية في قرنين من التحولات العربية",
    longDescription: "يستعرض الكتاب المرحلة من الغزو الفرنسي لمصر حتى اليوم مروراً بالاستعمار والاستقلال وموجات التحديث والتراجع.",
    author: "نور الدين الشريف",
    coverImageUrl: "https://images.unsplash.com/photo-1572072393749-3ca9c8ea0831?w=400",
    price: "31.99",
    isFeatured: false,
    tags: '{"تاريخ","عرب","سياسة"}',
  },
  // ── Psychology & Mind ─────────────────────────────────────────────────────
  {
    slug: "influence-cialdini-arabic",
    name: "التأثير — سيكولوجية الإقناع",
    category: "book" as const,
    description: "روبرت سيالديني — المبادئ الستة الكونية للإقناع",
    longDescription: "يكشف سيالديني عن الأسلحة السرية لعلم الإقناع ويشرح كيف تستخدمها المؤسسات ورجال المبيعات وكيف تحمي نفسك منها.",
    author: "روبرت سيالديني",
    coverImageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400",
    price: "29.99",
    isFeatured: false,
    tags: '{"سيكولوجية","إقناع","تأثير"}',
  },
  {
    slug: "emotional-intelligence-arabic",
    name: "الذكاء العاطفي",
    category: "book" as const,
    description: "دانيال غولمان — لماذا يهم أكثر من معدل الذكاء",
    longDescription: "يقدم غولمان مفهوم الذكاء العاطفي EQ ويثبت أن نجاح الفرد في الحياة يعتمد على وعيه وإدارته لمشاعره أكثر من درجة ذكائه المعرفي.",
    author: "دانيال غولمان",
    coverImageUrl: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=400",
    price: "28.99",
    isFeatured: false,
    tags: '{"سيكولوجية","مشاعر","نجاح"}',
  },
  {
    slug: "flow-csikszentmihalyi-arabic",
    name: "التدفق — سيكولوجية التجربة المثلى",
    category: "book" as const,
    description: "ميهاي تشيكسنتميهاي — سر السعادة الحقيقية",
    longDescription: "يكشف عالم النفس الشهير عن حالة التدفق التي يصف فيها كيف يشعر الإنسان بالسعادة التامة والإنتاجية القصوى.",
    author: "ميهاي تشيكسنتميهاي",
    coverImageUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400",
    price: "27.99",
    isFeatured: false,
    tags: '{"سيكولوجية","سعادة","إنتاجية"}',
  },
  {
    slug: "48-laws-of-power-arabic",
    name: "قوانين القوة الثمانية والأربعون",
    category: "book" as const,
    description: "روبرت غرين — الكتاب المرجعي لفهم الطبيعة البشرية والسلطة",
    longDescription: "يستخلص غرين من التاريخ والفلسفة والأدب قوانين السلطة الكونية مع أمثلة من التاريخ تمتد من إسكندر المقدوني إلى ماو تسي تونغ.",
    author: "روبرت غرين",
    coverImageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
    price: "37.99",
    isFeatured: true,
    tags: '{"سلطة","سيكولوجية","استراتيجية"}',
  },
  // ── Science & Nature ──────────────────────────────────────────────────────
  {
    slug: "brief-history-time-arabic",
    name: "تاريخ موجز للزمن",
    category: "book" as const,
    description: "ستيفن هوكينج — من الانفجار العظيم إلى الثقوب السوداء",
    longDescription: "يأخذنا هوكينج في رحلة عبر أعمق أسرار الكون — من نشأة الكون والثقوب السوداء إلى الأوتار الفائقة والبحث عن نظرية الكل.",
    author: "ستيفن هوكينج",
    coverImageUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400",
    price: "30.99",
    isFeatured: false,
    tags: '{"فيزياء","كون","علم"}',
  },
  {
    slug: "the-gene-mukherjee",
    name: "الجين — تاريخ حميم",
    category: "book" as const,
    description: "سيدهارتا موكرجي — رحلة عبر الحمض النووي والمستقبل البيولوجي",
    longDescription: "يروي موكرجي قصة اكتشاف الجين ويستكشف كيف تؤثر ثورة الجينوم على هويتنا وصحتنا ومستقبل النوع البشري.",
    author: "سيدهارتا موكرجي",
    coverImageUrl: "https://images.unsplash.com/photo-1530026454774-50cce722a1fb?w=400",
    price: "33.99",
    isFeatured: false,
    tags: '{"علم","أحياء","جينات"}',
  },
  {
    slug: "cosmos-sagan-arabic",
    name: "الكون",
    category: "book" as const,
    description: "كارل ساغان — رحلة شخصية عبر الفضاء والزمن",
    longDescription: "المصاحب الأدبي للسلسلة التلفزيونية الأيقونية، يستكشف ساغان الكون بعين الشاعر وعقل العالم في رحلة فلسفية علمية لا مثيل لها.",
    author: "كارل ساغان",
    coverImageUrl: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400",
    price: "29.99",
    isFeatured: false,
    tags: '{"فلك","كون","علم"}',
  },
  // ── Islamic & Spiritual ───────────────────────────────────────────────────
  {
    slug: "dont-be-sad-arabic",
    name: "لا تحزن",
    category: "book" as const,
    description: "عائض القرني — أكثر كتب التطوير الذاتي مبيعاً في العالم العربي",
    longDescription: "ملايين النسخ حول العالم ودعوة صادقة لمواجهة الحزن والقلق بسلاح الإيمان والعقل والأمل، مع آيات قرآنية وأحاديث نبوية وحكم إنسانية.",
    author: "عائض القرني",
    coverImageUrl: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=400",
    price: "19.99",
    isFeatured: false,
    tags: '{"إسلام","تطوير ذاتي","روحانيات"}',
  },
  {
    slug: "quranic-reflections",
    name: "تدبر القرآن الكريم",
    category: "book" as const,
    description: "تأملات ومعاني معاصرة في آيات الكتاب العزيز",
    longDescription: "مجموعة من التأملات القرآنية العميقة تربط بين المعاني الخالدة للآيات الكريمة والتحديات المعاصرة التي يواجهها الإنسان.",
    author: "محمد الغزالي",
    coverImageUrl: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400",
    price: "18.99",
    isFeatured: false,
    tags: '{"قرآن","إسلام","روحانيات"}',
  },
  {
    slug: "purification-of-soul",
    name: "تزكية النفس",
    category: "book" as const,
    description: "ابن القيم الجوزية — الطريق إلى تهذيب الروح",
    longDescription: "يستخلص من تراث ابن القيم الغزير جوهر تزكية النفس وتهذيب الأخلاق في منهج متكامل للسمو الروحي.",
    author: "ابن القيم الجوزية",
    coverImageUrl: "https://images.unsplash.com/photo-1567604944-24e5e0dd3c5e?w=400",
    price: "17.99",
    isFeatured: false,
    tags: '{"إسلام","أخلاق","روحانيات"}',
  },
  // ── Marketing & Communication ──────────────────────────────────────────────
  {
    slug: "made-to-stick-arabic",
    name: "أفكار تمسك وأخرى تُنسى",
    category: "book" as const,
    description: "تشيب هيث ودان هيث — لماذا بعض الأفكار تبقى وأخرى تموت",
    longDescription: "يحلل الكتاب الأفكار التي تستمر وتؤثر ويستخرج المبادئ الستة التي تجعل الرسائل لا تُنسى: بسيطة، مفاجئة، ملموسة، موثوقة، عاطفية، وحكائية.",
    author: "تشيب هيث ودان هيث",
    coverImageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400",
    price: "27.99",
    isFeatured: false,
    tags: '{"تسويق","تواصل","إبداع"}',
  },
  {
    slug: "contagious-berger",
    name: "الانتشار الفيروسي",
    category: "book" as const,
    description: "جونا برغر — لماذا تنتشر الأشياء",
    longDescription: "يكشف أستاذ التسويق جونا برغر عن العوامل الستة التي تجعل الأفكار والمنتجات والمحتوى ينتشر بشكل طبيعي بين الناس.",
    author: "جونا برغر",
    coverImageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400",
    price: "26.99",
    isFeatured: false,
    tags: '{"تسويق","وسائل التواصل","انتشار"}',
  },
  {
    slug: "digital-marketing-arabic",
    name: "التسويق الرقمي الشامل",
    category: "book" as const,
    description: "الدليل الكامل للتسويق عبر الإنترنت في السوق العربي",
    longDescription: "مرجع شامل يغطي SEO وSEM والتسويق بالمحتوى ووسائل التواصل الاجتماعي والتسويق بالعمولة مع حالات دراسية من السوق العربي.",
    author: "ريم العبدالله",
    coverImageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    price: "38.99",
    isFeatured: false,
    tags: '{"تسويق","رقمي","أعمال"}',
  },
  // ── Leadership & Management ───────────────────────────────────────────────
  {
    slug: "leaders-eat-last",
    name: "القادة يأكلون أخيراً",
    category: "book" as const,
    description: "سايمون سينك — لماذا تزدهر بعض الفرق وتفشل أخرى",
    longDescription: "يستكشف سينك لماذا يضحي بعض القادة بمصالحهم الشخصية من أجل فريقهم وكيف يبني هذا النوع من القيادة بيئات عمل استثنائية.",
    author: "سايمون سينك",
    coverImageUrl: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400",
    price: "30.99",
    isFeatured: false,
    tags: '{"قيادة","إدارة","فريق"}',
  },
  {
    slug: "extreme-ownership",
    name: "الملكية المطلقة",
    category: "book" as const,
    description: "جوكو ويلينك — دروس القيادة من ميادين الحرب",
    longDescription: "يأخذ ضباط مشاة البحرية الأمريكيين المبادئ التي طبقوها في أشد المعارك ضراوة ويطبقونها على بيئة الأعمال.",
    author: "جوكو ويلينك وليف بابين",
    coverImageUrl: "https://images.unsplash.com/photo-1529435980037-1efe9c1f7aec?w=400",
    price: "31.99",
    isFeatured: false,
    tags: '{"قيادة","إدارة","انضباط"}',
  },
  {
    slug: "how-to-win-friends",
    name: "كيف تكسب الأصدقاء وتؤثر في الناس",
    category: "book" as const,
    description: "ديل كارنيغي — الكلاسيكية الخالدة في فن العلاقات الإنسانية",
    longDescription: "أكثر من 30 مليون نسخة مباعة — يقدم كارنيغي مبادئ عملية مجربة لبناء علاقات إنسانية قوية وكسب التأثير والاحترام.",
    author: "ديل كارنيغي",
    coverImageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=400",
    price: "24.99",
    isFeatured: false,
    tags: '{"علاقات","تأثير","مهارات"}',
  },
  // ── Health & Wellness ─────────────────────────────────────────────────────
  {
    slug: "why-we-sleep",
    name: "لماذا ننام؟",
    category: "book" as const,
    description: "ماثيو ووكر — قوة النوم والأحلام",
    longDescription: "يكشف الكتاب العلمي الرائع عن أهمية النوم الجذرية لصحة الدماغ والجسم والوقاية من الأمراض، ويقدم استراتيجيات عملية للنوم الأفضل.",
    author: "ماثيو ووكر",
    coverImageUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=400",
    price: "28.99",
    isFeatured: false,
    tags: '{"صحة","نوم","دماغ"}',
  },
  {
    slug: "lifespan-sinclair",
    name: "عمر طويل — لماذا نشيخ وكيف لا نفعل ذلك",
    category: "book" as const,
    description: "ديفيد سينكلير — ثورة علم الشيخوخة",
    longDescription: "يطرح عالم الأحياء من هارفارد نظرية مثيرة تقول إن الشيخوخة مرض يمكن علاجه ويستعرض أحدث الأبحاث العلمية في إطالة العمر.",
    author: "ديفيد سينكلير",
    coverImageUrl: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=400",
    price: "33.99",
    isFeatured: false,
    tags: '{"صحة","طول عمر","علم"}',
  },
  {
    slug: "the-body-bill-bryson",
    name: "الجسم — دليل للمقيمين",
    category: "book" as const,
    description: "بيل برايسون — رحلة مذهلة داخل الجسم البشري",
    longDescription: "بأسلوبه الساحر المعهود يصحبنا برايسون في جولة داخل جسم الإنسان مستعرضاً عجائبه وأسراره العلمية بطريقة ترفيهية لا تُقاوم.",
    author: "بيل برايسون",
    coverImageUrl: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
    price: "29.99",
    isFeatured: false,
    tags: '{"صحة","علم","جسم بشري"}',
  },
  // ── Entrepreneurship & Startups ────────────────────────────────────────────
  {
    slug: "hard-thing-about-hard-things",
    name: "الأمر الصعب في الأشياء الصعبة",
    category: "book" as const,
    description: "بن هورويتز — بناء شركة عندما لا توجد إجابات سهلة",
    longDescription: "صراحة مذهلة من أحد أبرز المستثمرين في وادي السيليكون عن الجانب المؤلم من قيادة الشركات الناشئة — الأجزاء التي لا يتحدث عنها أحد.",
    author: "بن هورويتز",
    coverImageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400",
    price: "34.99",
    isFeatured: false,
    tags: '{"ريادة","أعمال","قيادة"}',
  },
  {
    slug: "shoe-dog",
    name: "صانع الأحذية",
    category: "book" as const,
    description: "فيل نايت — مذكرات مؤسس Nike",
    longDescription: "الرواية الملهمة لرحلة بناء إمبراطورية Nike من مؤسسها، بتفاصيل نادرة عن الشراكات والأزمات والقرارات التي غيرت مسار الرياضة العالمية.",
    author: "فيل نايت",
    coverImageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    price: "31.99",
    isFeatured: false,
    tags: '{"ريادة","مذكرات","نجاح"}',
  },
  {
    slug: "deliver-happiness",
    name: "تسليم السعادة",
    category: "book" as const,
    description: "توني شي — رحلة من الإفلاس إلى شركة بمليار دولار",
    longDescription: "يروي مؤسس Zappos رحلته من طفل رائد أعمال إلى بناء امبراطورية خدمة عملاء أعادت تعريف مفهوم ثقافة الشركة.",
    author: "توني شي",
    coverImageUrl: "https://images.unsplash.com/photo-1542744094-24638eff58bb?w=400",
    price: "28.99",
    isFeatured: false,
    tags: '{"ريادة","أعمال","سعادة"}',
  },
  // ── Education & Learning ───────────────────────────────────────────────────
  {
    slug: "ultralearning-young",
    name: "التعلم الفائق",
    category: "book" as const,
    description: "سكوت يونغ — استراتيجيات متقدمة لاكتساب المهارات",
    longDescription: "يكشف سكوت يونغ عن المبادئ التي سمحت له بإتقان المناهج الكاملة لـ MIT في سنة واحدة وتعلم أربع لغات في عام — منهج التعلم الذاتي الشرس.",
    author: "سكوت يونغ",
    coverImageUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400",
    price: "29.99",
    isFeatured: false,
    tags: '{"تعلم","مهارات","تطوير ذاتي"}',
  },
  {
    slug: "make-it-stick",
    name: "اجعله يعلق — علم التعلم الناجح",
    category: "book" as const,
    description: "بيتر براون وآخرون — العلم وراء التعلم الفعّال",
    longDescription: "يكشف علماء الإدراك عن حقائق مضادة للحدس حول أساليب التعلم الفعّال ويقدمون منهجاً علمياً للحفظ والاستيعاب العميق.",
    author: "بيتر براون",
    coverImageUrl: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=400",
    price: "26.99",
    isFeatured: false,
    tags: '{"تعلم","تعليم","دماغ"}',
  },
  // ── Writing & Creativity ───────────────────────────────────────────────────
  {
    slug: "big-magic-gilbert",
    name: "السحر الكبير — الحياة الإبداعية",
    category: "book" as const,
    description: "إليزابيث غيلبرت — الحياة خارج الخوف",
    longDescription: "تشارك مؤلفة Eat Pray Love رؤيتها الخاصة للإبداع وتدعوك لخوض حياة إبداعية جريئة بعيداً عن الخوف من الفشل والحكم.",
    author: "إليزابيث غيلبرت",
    coverImageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
    price: "25.99",
    isFeatured: false,
    tags: '{"إبداع","كتابة","إلهام"}',
  },
  {
    slug: "on-writing-king",
    name: "حول الكتابة",
    category: "book" as const,
    description: "ستيفن كينغ — مذكرات الحرفة",
    longDescription: "أشهر كتاب في تعليم الكتابة الإبداعية — يمزج كينغ بين مذكراته الشخصية وأسرار حرفة الكتابة في دليل لا يُقاوم لكل طامح في الكتابة.",
    author: "ستيفن كينغ",
    coverImageUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400",
    price: "26.99",
    isFeatured: false,
    tags: '{"كتابة","إبداع","فنون"}',
  },
  // ── Investment & Real Estate ───────────────────────────────────────────────
  {
    slug: "intelligent-investor",
    name: "المستثمر الذكي",
    category: "book" as const,
    description: "بنيامين غراهام — الكتاب المقدس للاستثمار القيمي",
    longDescription: "الكتاب الذي وصفه وارن بافيت بأنه أفضل كتاب في الاستثمار على الإطلاق — يشرح مبادئ الاستثمار القيمي الخالدة التي أثبتت جدارتها عبر عقود.",
    author: "بنيامين غراهام",
    coverImageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400",
    price: "38.99",
    isFeatured: true,
    tags: '{"استثمار","مال","بورصة"}',
  },
  {
    slug: "one-up-on-wall-street",
    name: "تفوق على وول ستريت",
    category: "book" as const,
    description: "بيتر لينش — كيف يستخدم المستثمر العادي ميزته",
    longDescription: "يشرح مدير الصندوق الأنجح في التاريخ كيف يمكن للمستثمر العادي التفوق على محترفي وول ستريت باستخدام معرفته اليومية.",
    author: "بيتر لينش",
    coverImageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400",
    price: "33.99",
    isFeatured: false,
    tags: '{"استثمار","بورصة","مال"}',
  },
];

export async function seedSouqProducts() {
  const existing = await db.select({ slug: souqProductsTable.slug }).from(souqProductsTable);
  const existingSlugs = new Set(existing.map((p) => p.slug));
  const toInsert = BOOKS_SEED.filter((b) => !existingSlugs.has(b.slug));

  if (toInsert.length === 0) {
    logger.info("Souq products already seeded — skipping");
    return;
  }

  await db.insert(souqProductsTable).values(
    toInsert.map((b) => ({
      name: b.name,
      slug: b.slug,
      category: b.category,
      description: b.description,
      longDescription: b.longDescription,
      author: b.author,
      coverImageUrl: b.coverImageUrl,
      fileUrl: "",
      previewUrl: "",
      price: b.price,
      isActive: true,
      isFeatured: b.isFeatured,
      tags: b.tags,
    }))
  );

  logger.info({ count: toInsert.length }, "Seeded souq products");
}
